services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama  # Persistent model storage
    entrypoint: >
      bash -c "
      ollama serve &
      sleep 10 &&
      ollama run llama3.2:3b &&
      wait
      "

  api:
    build: .
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

volumes:
  ollama_data: