services:
    mongo:
        image: mongo:latest
        volumes:
            - mongodb_data:/data/db

    vector_bd:
        build: .
        ports:
            - "3006:3006"
        volumes:
            - type: bind
              source: unprocessed_files/
              target: /unprocessed_files/
            - type: bind
              source: modify_files/
              target: /modify_files/
        depends_on:
            - mongo
volumes:
    mongodb_data: